[package]
name = "muti-rm"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = "0.17.11"
walkdir = "2.5.0"
clap = { version = "4.5.30", features = ["derive"] }
crossbeam-channel = "0.5.14"
num_cpus = "1.16.0"
