name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-x86${{ hashFiles('**/Cargo.lock') }}
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose -r
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.0
      with:
        name: muti-rm-x86
        path: target/release/muti-rm
  build-linux-arm:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-arm${{ hashFiles('**/Cargo.lock') }}
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose -r
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.0
      with:
        name: muti-rm-arm
        path: target/release/muti-rm
